# -*- coding: utf-8 -*-
"""Decision Tree Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1za7uz-3CS0muwuMjODPBEEcvGvwh1vpg

# Decision Tree Regression

## Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing Data Set"""

dataset = pd.read_csv('/content/Data Decision Tree Regre.csv')
X = dataset.iloc[:, 1:-1].values #indexes values in a dataframe
y = dataset.iloc[:, -1].values

print(X)
print(y)

"""## Training the dataset"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 21)
regressor.fit(X,y)

"""## Predicting a new result"""

# If your data has a single feature
input_data = np.array([5.5]).reshape(-1, 1)


# Now, you can use the predict function with the reshaped input data
predictions = regressor.predict(input_data)

regressor.predict([[5.5]])

"""## Visualising the Decision Tree Regression"""

X_grid = np.arange(min(X), max(X), 0.01) #smoothing the graph w inc of 0.01
X_grid = X_grid.reshape((len(X_grid), 1)) #rehsaping
plt.scatter(X, y, color = 'red') #we get continous values
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Decision Tree Regression')
plt.xlabel('Grade')
plt.ylabel('Salary')
plt.show()