# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u3ekEoe7hxFipsLv1YZ_eC-hwq6cvj2J

# Multiple Linear Regression

## Importing Libraries
"""

import numpy as py
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing Data Set"""

data_set = pd.read_csv("/content/Covid_data.csv")
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

"""## Encoding categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = py.array(ct.fit_transform(X))

"""## Splitting into test and training set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

"""## Training the Multiple Linear Regression model on the Training set"""



from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
py.set_printoptions(precision = 3)
print(py.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

"""## Visualizing results"""

plt.plot(y_pred)
plt.plot(y_test)
plt.show()