# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkWTp9nSo6nbMyYP3IxoYAwID9A4qKAM

# Simple Linear Regression

## Importing Libraries
"""

import numpy as py
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing Data Set"""

data_set = pd.read_csv("/content/ Salary_data.csv")
X = data_set.iloc[:, :-1].values
y = data_set.iloc[:, -1].values

"""## Splitting into test and training set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

"""## Training on Training Set using Simple Linear Regression"""

from sklearn.linear_model import LinearRegression

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train) # Basis on linear regression to see the relationship between x and y

"""## Prediction on Test Set"""

y_pred = regressor.predict(X_test)

"""## Visualizing the Training Set"""

plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color= 'blue')
plt.title("ctc vs years of experience ")
plt.xlabel("experience")
plt.ylabel("ctc")
plt.show()

"""## Visualizing the Test Set"""

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color= 'blue')
plt.title("ctc vs years of experience ")
plt.xlabel("experience")
plt.ylabel("ctc")
plt.show()